POST http://localhost:3001/api/persons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTAxYjM0ZjJiMGUzYjVhMjBlNjFiMCIsInVzZXJuYW1lIjoicGVyZHVyYWJvMiIsImlhdCI6MTY1ODg1NDIwMywiZXhwIjoxNjU5NDU5MDAzfQ.Eo6iymPEQdsc1Fb0KsHs5rPYbLoHgEc4jyfWFbDIIe0

{
	"name": "John Dee",
	"number": "606-5435443"
}